
#' Plot EIR(t) *vs.* the PR(t)
#'
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] that specifies `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a [logical] to plot add_axes only if FALSE
#'
#' @export
plot_eirVpr <- function(pars, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
  with(vars$terms,{
    aeir = 365*eir
      plot(aeir, pr, type = "l", xaxt="n", lty = llty,
           xlab = "aEIR", ylab = "PR",
           xlim = range(0, aeir), ylim = c(0,1), col = clrs)
      axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  })
  lines_eirVpr(vars$terms, pars, clrs, llty)
}

#' Add lines for the EIR(t) *vs.* the PR(t)
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
lines_eirVpr <- function(terms, pars, clrs= "black", llty = 1){
  with(terms,{
    aeir = 365*eir
    if(pars$nStrata==1) lines(aeir, pr, col=clrs[1], lty = llty[1])
    if(pars$nStrata>1){
      if(length(clrs)==1) clrs=rep(clrs, pars$nStrata)
      if(length(llty)==1) llty=rep(llty, pars$nStrata)
      for(i in 1:pars$nStrata)
        lines(aeir[,i], pr[,i], col=clrs[i], lty = llty[i])
  }})
}

#' Plot the eir-pr scaling relationship
#'
#' @param pars a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [character] vector of colors
#' @param llty a [list]
#'
#' @export
plot_eirpr <- function(pars, clrs= "black", llty = 1){
  with(pars$outputs$eirpr, {
    plot(aeir, pr, type = "l", xaxt="n", lty = llty,
         xlab = "aEIR", ylab = "PR", log="x",
         xlim = range(aeir), ylim = c(0,1),
         col = clrs)
    axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  })
}

#' Add lines for an eir-pr scaling relationship
#'
#' @param pars a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [character] vector of colors
#' @param llty a [list]
#'
#' @export
lines_eirpr <- function(pars, clrs= "black", llty = 1){
  with(pars$outputs$eirpr, lines(aeir, pr, col = clrs, lty = llty))
}
