
#' Plot the EIR *vs.* time
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add a [logical] to plot axes only if FALSE
#'
#' @export
plot_EIR <- function(model, clrs="black", llty=1, stable=FALSE, add=FALSE){
  vars=with(model$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add==FALSE)
  with(vars$terms,{
    plot(time, eir, type = "n", xlab = "Time", ylab = "dEIR", ylim = range(0, eir))
    tk4 = pretty(365*eir)
    clr = "darkblue"
    axis(4, tk4, tk4, col=clr, col.axis =clr)
    mtext("aEIR", 4, -1.5, col = clr)
  })
  lines_EIR(vars$terms, model, clrs, llty)
}

#' Add lines for the EIR *vs.* time
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#'
#' @export
lines_EIR <- function(terms, model, clrs="black", llty=1){
  with(terms,{
    if(model$nStrata==1)
      lines(time, eir, col=clrs, lty = llty)
    if(model$nStrata>1){
      if(length(clrs)==1) clrs=rep(clrs, model$nStrata)
      if(length(llty)==1) llty=rep(llty, model$nStrata)
      for(i in 1:model$nStrata)
        lines(time, eir[,i], col=clrs[i], lty = llty)
    }
  })
}

#' PLot the aEIR *vs.* time
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add a [logical] to plot axes only if FALSE
#'
#' @export
plot_aEIR <- function(model, clrs="black", llty=1, stable=FALSE, add=FALSE){
  vars=with(model$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add==FALSE)
  with(vars$terms,{
    aeir = 365*eir
    plot(time, aeir, type = "n", xlab = "Time", ylab = "aEIR", ylim = range(0, aeir))
  })
  lines_aEIR(vars$terms, model, clrs, llty)
}

#' Add lines for the aEIR *vs.* time
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#'
#' @export
lines_aEIR <- function(terms, model, clrs="black", llty=1){
  with(terms,{
    aeir = 365*eir
    if(model$nStrata==1) lines(time, aeir, col=clrs)
    if(model$nStrata>1){
      if (length(clrs)==1) clrs=rep(clrs, model$nStrata)
      for(i in 1:model$nStrata)
        lines(time, aeir[,i], col=clrs[i])
    }
  })
}

#' Plot EIR(t) *vs.* the PR(t)
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] that specifies `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add a [logical] to plot axes only if FALSE
#'
#' @export
plot_eirVpr <- function(model, clrs="black", llty=1, stable=FALSE, add=FALSE){
  vars=with(model$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add==FALSE)
  with(vars$terms,{
    aeir = 365*eir
      plot(aeir, pr, type = "l", xaxt="n", lty = llty,
           xlab = "aEIR", ylab = "PR",
           xlim = range(0, aeir), ylim = c(0,1), col = clrs)
      axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  })
  lines_eirVpr(vars$terms, model, clrs, llty)
}

#' Add lines for the EIR(t) *vs.* the PR(t)
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
lines_eirVpr <- function(terms, model, clrs= "black", llty = 1){
  with(terms,{
    aeir = 365*eir
    if(model$nStrata==1) lines(aeir, pr, col=clrs[1], lty = llty[1])
    if(model$nStrata>1){
      if(length(clrs)==1) clrs=rep(clrs, model$nStrata)
      if(length(llty)==1) llty=rep(llty, model$nStrata)
      for(i in 1:model$nStrata)
        lines(aeir[,i], pr[,i], col=clrs[i], lty = llty[i])
  }})
}

#' Basic plotting: plot the true PR.
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add a [logical] to plot axes only if FALSE
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
plot_PR = function(model, clrs="black", llty=1, stable=FALSE, add=FALSE){
  vars=with(model$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add==FALSE)
  with(vars$terms,
       plot(time, 0*time + 1, type = "n", ylim = c(0,1),
            ylab = "# Infected", xlab = "Time"))

  lines_PR(vars$terms, model, clrs, llty)
}

#' Add the orbits for the SIS model to a plot for models of human infection and immunity
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
lines_PR = function(terms, model, clrs="black", llty=1){
  with(terms,{
    if(model$nStrata==1) lines(time, pr, col=clrs)
    if(model$nStrata>1){
      if (length(clrs)==1) clrs=rep(clrs, model$nStrata)
      for(i in 1:model$nStrata)
        lines(time, pr[,i], col=clrs[i])
    }
  })
}


#' Plot the eir-pr scaling relationship
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty a [list]
#'
#' @export
plot_eirpr <- function(model, clrs= "black", llty = 1){
  with(model$outputs$eirpr, {
    plot(aeir, pr, type = "l", xaxt="n", lty = llty,
         xlab = "aEIR", ylab = "PR", log="x",
         xlim = range(aeir), ylim = c(0,1),
         col = clrs)
    axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  })
}

#' Add lines for an eir-pr scaling relationship
#'
#' @param model a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [list] of colors for plotting
#' @param llty a [list]
#'
#' @export
lines_eirpr <- function(model, clrs= "black", llty = 1){
  with(model$outputs$eirpr, lines(aeir, pr, col = clrs, lty = llty))
}
