
#' Plot EIR(t) *vs.* the PR(t)
#'
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param i the host species index
#' @param clrs a [character] vector of colors
#' @param llty an [integer] that specifies `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a [logical] to plot add_axes only if FALSE
#'
#' @export
plot_eirVpr <- function(pars, i=1, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  pr = vars$terms$pr[[i]]
  eir = vars$terms$eir[[i]]
  aeir = 365*eir
  if(add_axes==TRUE){
    plot(aeir, pr, type = "n", xaxt="n", lty = llty,
           xlab = "aEIR", ylab = "PR",
           xlim = range(0, aeir), ylim = c(0,1), col = clrs)
      graphics::axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  }
  lines_eirVpr(eir, pr, pars$Hpar[[i]]$nStrata, clrs, llty)
}

#' Add lines for the EIR(t) *vs.* the PR(t)
#'
#' @param eir the daily EIR
#' @param pr the parasite rate
#' @param nStrata the number of population strata
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
lines_eirVpr <- function(eir, pr, nStrata, clrs= "black", llty = 1){
    aeir = 365*eir
    if(nStrata==1)
      graphics::lines(aeir, pr, col=clrs[1], lty = llty[1])
    if(nStrata>1){
      if(length(clrs)==1) clrs=rep(clrs, nStrata)
      if(length(llty)==1) llty=rep(llty, nStrata)
      for(i in 1:nStrata)
        graphics::lines(aeir[,i], pr[,i], col=clrs[i], lty = llty[i])
  }
}

#' Plot the eir-pr scaling relationship
#'
#' @param pars a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [character] vector of colors
#' @param llty a [list]
#'
#' @export
plot_eirpr <- function(pars, clrs= "black", llty = 1){
  with(pars$outputs$eirpr, {
    plot(aeir, pr, type = "l", xaxt="n", lty = llty,
         xlab = "aEIR", ylab = "PR", log="x",
         xlim = range(aeir), ylim = c(0,1),
         col = clrs)
    graphics::axis(1, 10^c(-1:3), c(".1", "1", "10", "100","1000"))
  })
}

#' Add lines for an eir-pr scaling relationship
#'
#' @param pars a [list] *e.g.*,  generated by `exDE::xde_setup()` that defines a model in `exDE`
#' @param clrs a [character] vector of colors
#' @param llty a [list]
#'
#' @export
lines_eirpr <- function(pars, clrs= "black", llty = 1){
  with(pars$outputs$eirpr, graphics::lines(aeir, pr, col = clrs, lty = llty))
}
